### ISSUE TITLE
PyPi version outdated

### ISSUE THREAD

**Issue by gutzbenj** [wmo-cop/pyoscar#3]
Hey there, thanks for the effort to bring this powerful tool to Python. Unfortunately the examples given in the README are outdated for the PyPi version.

For example
`pyoscar station --identifier 0-20000-0-71151
`
does not work under the PyPI verison. Can you create a new release for the current version?

**Comment by tomkralidis** [comment]
Hi: sorry for the delay.  0.3.0 now published to PyPI: https://pypi.org/project/pyoscar/0.3.0/

**Comment by gutzbenj** [comment]
Thanks a lot!
