### ISSUE TITLE
Upload xml-files without using gml id for Data URL after latest OSCAR/Surface release 1.8.4

### ISSUE THREAD

**Issue by simonebircher** [wmo-cop/pyoscar#6]
Dear Tom
I have been using pyoscar with great success to upload xml-files to OSCAR/Surface containing instrument metadata of the EUMETNET E-PROFILE network. With the last OSCAR/Surface release 1.8.4. this September, a new feature was implemented leading to the fact that the field "Data URL" under Deployment (Observations/Measurements par) is not filled anymore even if my xml files still contain the respective information. According to Lucia Cappelletti (MeteoSwiss) this is due to the fact that with the new release several Data URLs can now be provided and therefore a respective gml id has been introduced. Nevertheless, it is still possible to submit the xml files without such a corresponding gml id, but in that case, the POST Request during the upload has to be supplemented with the parameter «UseOnlyGmlIds=FALSE». Would it be possible for you to implement this in pyoscar?
In advance, thanks so much for your feedback and best regards
Simone

**Comment by tomkralidis** [comment]
Hi @simonebircher thanks for the info.  pyoscar should be sending `useOnlyGmlIds=FALSE` by default as part of metadata uploading.  Examples below:

```bash
# useOnlyGmlIds=FALSE
pyoscar upload -x /path/to/wmdr.xml -at API_TOKEN -e prod -l results.log
# useOnlyGmlIds=TRUE
pyoscar upload -x /path/to/wmdr.xml -at API_TOKEN -e prod -l results.log -g
```

Having said this, what version of pyoscar are you using?

**Comment by simonebircher** [comment]
Hi @tomkralidis thanks a lot for your feedback. I am using pyoscar version 0.4.0
This is what I get when trying to upload the attached file to OSCAR/Surface DEPL:
Try XML file upload to OSCAR/Surface for /home/simone/Desktop/eprofile2oscar/test_upload/0-20000-0-06602.xml
XML Upload to OSCAR/Surface was successful for /home/simone/Desktop/eprofile2oscar/test_upload/0-20000-0-06602.xml
xmlStatus: VALID_XML_WITH_ERRORS_OR_WARNINGS
The list below is organized by section header and shows exceptions/issues – if any – that may have resulted from the processing of the XML (NB: Section headers are always displayed).
# ObservingCapability of facility with identifier "0-20000-0-06602"
REF_6: The selected identification process is using the ID attribute. No value found for the ID attribute of the element "result/ResultSet/distributionInfo/MD_Distribution/transferOptions/MD_DigitalTransferOptions/onLine/CI_OnlineResource/linkage/URL with gml:description "Archive"". The element is discarded.
# ObservingCapability of facility with identifier "0-20000-0-06602"
REF_6: The selected identification process is using the ID attribute. No value found for the ID attribute of the element "result/ResultSet/distributionInfo/MD_Distribution/transferOptions/MD_DigitalTransferOptions/onLine/CI_OnlineResource/linkage/URL with gml:description "Archive"". The element is discarded.
[0-20000-0-06602.xml.zip](https://github.com/wmo-cop/pyoscar/files/10545032/0-20000-0-06602.xml.zip)
If I copy-paste the xml-file content in the xml submission field in the OSCAR/Surface GUI and untick the box "use gml:id matching only" I don't get the above message. It indicates the upload status "SUCCESS" and the field "data URL" under Deployments displays correctly, while it is not appearing after the upload using pyoscar where I get the above upload warning message.
Any help from your side is well appreciated to find out what is going wrong here, thanks a lot in advance!
All the best
Simone

**Comment by fstuerzl** [comment]
Hi @simonebircher , hi @tomkralidis,

I had the same issue (also using version 0.4.0), but when I explicitely set the parameter «only_use_gml_ids» to «False» it worked:
```
response = client.upload(data, only_use_gml_ids = False)
```
Looking at the pyoscar source code, I think, I have an idea, why it doesn't work for us without setting this parameter. 
Simone and I both call the upload function from a script, not from the terminal like your example suggests.
In the definition of the OSCARClient class the upload function is defined with parameter «only_use_gml_ids» as «True» by default:
```
def upload(self, xml_data: str, only_use_gml_ids: bool = True) -> dict:
```
(l. 287, https://github.com/wmo-cop/pyoscar/blob/master/pyoscar/__init__.py)

In the "click commands" below, it is the opposite - and this function probably what is used, when you call pyoscar from the terminal. 
```
def upload(ctx, api_token, env, xml, log, only_use_gml_ids=False,
           verbosity=None):
```
(see l. 428f)
This is inconsistent, as far as I understand. Or was there some reason behind it?

Generally, I'd prefer "True" as the default value, so that it matches the OSCAR GUI (with the remark "use gml:id matching only (consult user manual before unchecking the box)").

**Comment by tomkralidis** [comment]
@simonebircher @fstuerzl thanks for the feedback.  I've updated the CLI to set using GML ids to TRUE by default.

Updated CLI:

```bash
# useOnlyGmlIds=TRUE (no explicit parameters needed)
pyoscar upload -x /path/to/wmdr.xml -at API_TOKEN -e prod -l results.log
# useOnlyGmlIds=FALSE
pyoscar upload -x /path/to/wmdr.xml -at API_TOKEN -e prod -l results.log --no-gml-ids
```

Can you test and verify using latest master branch?  We can re-open this issue if needed.  Thanks!
